update szablony
ivall/VIshop-wiki pull request #11
Opened 2023-04-08 07:58 UTC by robalmeister

2023-04-09 19:19 UTC, nwseOOO commented
chujowe

2023-04-09 19:55 UTC, robalmeister commented
zrob lepsze

2023-04-10 18:47 UTC, ivall requested changes
Do wywalenia ogłoszenie o wersji nginx

2023-05-07 21:08 UTC, ivall requested changes
Parametr `--dry-run` jedynie pokaże kroki jakie zostaną wykonane podczas instalacji. Parametr do wywalenia.

2023-05-18 20:39 UTC, merged